security:
    encoders:
        App\Entity\Utilisateur: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        database_users:
            entity: { class: App\Entity\Utilisateur, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            user_checker: App\Security\UserChecker
            anonymous: true
            form_login:
                check_path: security_login
                login_path: security_login
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /
            logout:
                path: security_logout
                target: security_login
    access_control:
        - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY,  }
        - { path: '^/', roles: ROLE_SUPER_ADMIN }