vich_uploader:
    db_driver: orm

    mappings:
        ged:
            uri_prefix: /GED/NDF
            upload_destination: '%kernel.project_dir%/public/GED/NDF'
            #upload_destination: '%kernel.project_dir%/../DB/GED'
            directory_namer: App\Service\DirectoryNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        document:
            uri_prefix: /GED/SOCIETE
            upload_destination: '%kernel.project_dir%/public/GED/SOCIETE'
            #upload_destination: '%kernel.project_dir%/../DB/GED'
            directory_namer: App\Service\DocumentNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
