index:
    path: /
    controller: App\Controller\ExampleController::index



#securité




cra:
    path: /cra
    controller: App\Controller\CraController::index
frais :
    path: /frais
    controller: App\Controller\FraisController::index
frais_new:
    path: /frais/new
    controller: App\Controller\FraisController::new
frais_edit:
    path: /frais/edit/{id}
    controller: App\Controller\FraisController::edit
    requirements:
        page: '\d+'
frais_delete:
    path: /frais/delete/{id}
    controller: App\Controller\FraisController::delete
    requirements:
        page: '\d+'
frais_duplique:
    path: /frais/duplique/{id}
    controller: App\Controller\FraisController::dupliquer
    requirements:
        page: '\d+'







facturation :
    path: /facturation
    controller: App\Controller\FacturationController::index
tbbord :
    path: /tbbord
    controller: App\Controller\TbBordController::index
ged :
    path: /ged
    controller: App\Controller\GedController::index
user:
    path: /user
    controller: App\Controller\UserController::index
user_new:
    path: /user/new
    controller: App\Controller\UserController::new
profil :
    path: /profil
    controller: App\Controller\ProfilController::index

acl :
    path: /acl
    controller: App\Controller\AclController::index

tva :
    path: /tva
    controller: App\Controller\TvaController::index

holidays :
    path: /holidays
    controller: App\Controller\HolidayController::index
