index:
    path: /
    controller: App\Controller\ExampleController::index
login:
    path: /login
    controller:  App\Controller\SecurityController::login
cra:
    path: /cra
    controller: App\Controller\CraController::index
frais :
    path: /frais
    controller: App\Controller\FraisController::index
frais_new:
    path: /frais/new
    controller: App\Controller\FraisController::new







facturation :
    path: /facturation
    controller: App\Controller\FacturationController::index
tbbord :
    path: /tbbord
    controller: App\Controller\TbBordController::index
ged :
    path: /ged
    controller: App\Controller\GedController::index
user :
    path: /user
    controller: App\Controller\UserController::index
profil :
    path: /profil
    controller: App\Controller\ProfilController::index

acl :
    path: /acl
    controller: App\Controller\AclController::index

tva :
    path: /tva
    controller: App\Controller\TvaController::index

holidays :
    path: /holidays
    controller: App\Controller\HolidayController::index
