tbbord :
    path: /
    controller: App\Controller\TbBordController::index


cra:
    path: /cra
    controller: App\Controller\CraController::index
#frais
frais :
    path: /frais
    controller: App\Controller\FraisController::index
frais_new:
    path: /frais/new
    controller: App\Controller\FraisController::new
frais_edit:
    path: /frais/edit/{id}
    controller: App\Controller\FraisController::edit
    requirements:
        page: '\d+'
frais_delete:
    path: /frais/delete/{id}
    controller: App\Controller\FraisController::delete
    requirements:
        page: '\d+'
frais_duplique:
    path: /frais/duplique/{id}
    controller: App\Controller\FraisController::dupliquer
    requirements:
        id: '\d+'

#Clients
client:
    path: /client
    controller: App\Controller\ClientController::index

client_new:
    path: /client/new
    controller: App\Controller\ClientController::new
client_edit:
    path: /client/edit/{id}
    controller: App\Controller\ClientController::edit
    requirements:
        id: '\d+'
client_delete:
    path: /client/delete/{id}
    controller: App\Controller\ClientController::delete
    requirements:
        id: '\d+'

#societe
societe:
    path: /societe
    controller: App\Controller\SocieteController::index
societe_edit:
    path: /societe/edit/{id}
    controller: App\Controller\SocieteController::edit
    requirements:
        id: '\d+'
#Document
document:
    path: /document
    controller: App\Controller\DocumentController::index
document_new:
    path: /document/new
    controller: App\Controller\DocumentController::new
document_edit:
    path: /document/edit/{id}
    controller: App\Controller\DocumentController::edit
    requirements:
        id: '\d+'

document_delete:
    path: /document/delete/{id}
    controller: App\Controller\DocumentController::delete
    requirements:
        id: '\d+'
#Facturation
facturation :
    path: /facturation
    controller: App\Controller\FacturationController::index


ged :
    path: /ged
    controller: App\Controller\GedController::index
#Utilisateurs
user:
    path: /user
    controller: App\Controller\UserController::index
user_new:
    path: /user/new
    controller: App\Controller\UserController::new
user_edit:
    path: /user/edit/{id}
    controller: App\Controller\UserController::edit
    requirements:
        id: '\d+'
user_delete:
    path: /user/delete/{id}
    controller: App\Controller\UserController::delete
    requirements:
        id: '\d+'

profil :
    path: /profil
    controller: App\Controller\ProfilController::index

acl :
    path: /acl
    controller: App\Controller\AclController::index

tva :
    path: /tva
    controller: App\Controller\TvaController::index

holidays :
    path: /holidays
    controller: App\Controller\HolidayController::index
